version: "3.1"
services:
  # APP*****************************************
  myworkouts:
    build: ./
    image: myworkouts
    network_mode: host
    container_name: myworkouts
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "/var/services/homes/mira/Drive/Apps/MyWorkouts/logs:/usr/app/logs"
      - "/var/services/homes/mira/Drive/Apps/MyWorkouts/img:/usr/app/img"
    restart: unless-stopped