version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_for_my_apps
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=macos
      - POSTGRES_USER=webappuser
      - POSTGRES_DB=my_workouts
    volumes:
      - "C:/Users/mira1/IdeaProjects/MyWorkouts/PostgreData:/var/lib/postgresql/data"
      - "C:/Users/mira1/IdeaProjects/MyWorkouts/PostgreData:/docker-entrypoint-initdb.d"
    restart: unless-stopped