CREATE TABLE privilege
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_privilege PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE role_privilege
(
    privilege_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL
);

CREATE TABLE tanita_last_update
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tanita_last_update PRIMARY KEY (id)
);

CREATE TABLE tanita_measurement
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date              TIMESTAMP WITHOUT TIME ZONE,
    weight            DOUBLE PRECISION                        NOT NULL,
    bmi               DOUBLE PRECISION                        NOT NULL,
    body_fat          DOUBLE PRECISION                        NOT NULL,
    body_fat_mass     DOUBLE PRECISION                        NOT NULL,
    visceral_fat      DOUBLE PRECISION                        NOT NULL,
    muscle_mass       DOUBLE PRECISION                        NOT NULL,
    muscle_mass_ratio DOUBLE PRECISION                        NOT NULL,
    muscle_quality    DOUBLE PRECISION                        NOT NULL,
    bone_mass         DOUBLE PRECISION                        NOT NULL,
    bmr               DOUBLE PRECISION                        NOT NULL,
    metabolic_age     DOUBLE PRECISION                        NOT NULL,
    body_watter       DOUBLE PRECISION                        NOT NULL,
    body_watter_mass  DOUBLE PRECISION                        NOT NULL,
    physique_rating   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_tanita_measurement PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE withings_measurements
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date              TIMESTAMP WITHOUT TIME ZONE,
    weight            DOUBLE PRECISION                        NOT NULL,
    fat_free_mass     DOUBLE PRECISION                        NOT NULL,
    fat_ratio         DOUBLE PRECISION                        NOT NULL,
    fat_mass_weight   DOUBLE PRECISION                        NOT NULL,
    muscle_mass       DOUBLE PRECISION                        NOT NULL,
    muscle_mass_ratio DOUBLE PRECISION                        NOT NULL,
    hydration         DOUBLE PRECISION                        NOT NULL,
    hydration_ratio   DOUBLE PRECISION                        NOT NULL,
    bone_mass         DOUBLE PRECISION                        NOT NULL,
    bmi               DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_withings_measurements PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE role_privilege
    ADD CONSTRAINT fk_rolpri_on_privilege FOREIGN KEY (privilege_id) REFERENCES privilege (id);

ALTER TABLE role_privilege
    ADD CONSTRAINT fk_rolpri_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);